sudo: false
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
before_install:
  - 'npm install -g npm@latest'
after_success:
  - 'npm test && ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
